name: fe_snappix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Person1.png
    - assets/images/Person2.png
    - assets/images/Person3.png
    - assets/images/Person4.png
    - assets/images/Person5.png
    - assets/images/Snappix.png
