name: fe_snappix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.0
  http: ^1.5.0
  http_parser: ^4.0.2
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/chat.svg
    - assets/icons/like-fill.svg
    - assets/icons/like-outline.svg
    - assets/images/Person1.png
    - assets/images/Person2.png
    - assets/images/Person3.png
    - assets/images/Person4.png
    - assets/images/Person5.png
    - assets/images/Snappix.png
